export default {
    ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
    ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
    ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
    ON_SIGNUP_SUCCESS: "ON_SIGNUP_SUCCESS",
    ON_SIGNUP_FAIL: "ON_SIGNUP_FAIL",
    ON_FILTER_SUCCESS: "ON_FILTER_SUCCESS",
    WISHLIST_SUCCESS: "WISHLIST_SUCCESS",
    WISHLIST_FAILED: "WISHLIST_FAILED",
    LIKE_COUNT: "LIKE_COUNT"
}